/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PlayerRouteRouteImport } from './routes/player/route'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as PlayerChesscomRouteImport } from './routes/player/chesscom'
import { Route as PlayerHistoryRouteImport } from './routes/player/history'
import { Route as PlayerLichessRouteImport } from './routes/player/lichess'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRouteRoute = PlayerRouteRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerChesscomRoute = PlayerChesscomRouteImport.update({
  id: '/chesscom',
  path: '/chesscom',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerHistoryRoute = PlayerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PlayerRouteRoute,
} as any)
const PlayerLichessRoute = PlayerLichessRouteImport.update({
  id: '/lichess',
  path: '/lichess',
  getParentRoute: () => PlayerRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteRouteWithChildren
  '/legal': typeof LegalRoute
  '/player/chesscom': typeof PlayerChesscomRoute
  '/player/history': typeof PlayerHistoryRoute
  '/player/lichess': typeof PlayerLichessRoute
  '/player/': typeof PlayerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/player/chesscom': typeof PlayerChesscomRoute
  '/player/history': typeof PlayerHistoryRoute
  '/player/lichess': typeof PlayerLichessRoute
  '/player': typeof PlayerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteRouteWithChildren
  '/legal': typeof LegalRoute
  '/player/chesscom': typeof PlayerChesscomRoute
  '/player/history': typeof PlayerHistoryRoute
  '/player/lichess': typeof PlayerLichessRoute
  '/player/': typeof PlayerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/player'
    | '/legal'
    | '/player/chesscom'
    | '/player/history'
    | '/player/lichess'
    | '/player/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/player/chesscom'
    | '/player/history'
    | '/player/lichess'
    | '/player'
  id:
    | '__root__'
    | '/'
    | '/player'
    | '/legal'
    | '/player/chesscom'
    | '/player/history'
    | '/player/lichess'
    | '/player/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerRouteRoute: typeof PlayerRouteRouteWithChildren
  LegalRoute: typeof LegalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player/chesscom': {
      id: '/player/chesscom'
      path: '/chesscom'
      fullPath: '/player/chesscom'
      preLoaderRoute: typeof PlayerChesscomRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player/history': {
      id: '/player/history'
      path: '/history'
      fullPath: '/player/history'
      preLoaderRoute: typeof PlayerHistoryRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
    '/player/lichess': {
      id: '/player/lichess'
      path: '/lichess'
      fullPath: '/player/lichess'
      preLoaderRoute: typeof PlayerLichessRouteImport
      parentRoute: typeof PlayerRouteRoute
    }
  }
}

interface PlayerRouteRouteChildren {
  PlayerChesscomRoute: typeof PlayerChesscomRoute
  PlayerHistoryRoute: typeof PlayerHistoryRoute
  PlayerLichessRoute: typeof PlayerLichessRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
}

const PlayerRouteRouteChildren: PlayerRouteRouteChildren = {
  PlayerChesscomRoute: PlayerChesscomRoute,
  PlayerHistoryRoute: PlayerHistoryRoute,
  PlayerLichessRoute: PlayerLichessRoute,
  PlayerIndexRoute: PlayerIndexRoute,
}

const PlayerRouteRouteWithChildren = PlayerRouteRoute._addFileChildren(
  PlayerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerRouteRoute: PlayerRouteRouteWithChildren,
  LegalRoute: LegalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
